### ISSUE TITLE
Sharing to whatsapp crashes whatsapp

### ISSUE THREAD

**Issue by thusoy** [megacool/sdk#17]
Stacktrace:
```
Shutting down VM
FATAL EXCEPTION: main
Process: com.whatsapp, PID: 26469
java.lang.SecurityException: Permission Denial: reading co.megacool.megacool.MegacoolFileProvider uri content://co.megacool.spritybird2.megacool_file_provider/gifs/C21F969B5F03D33D43E04F8F136E7682/megacool.gif?caption=Customsharetext%20yo!%0Ahttps%3A%2F%2Fmgcl.co%2Fsprity2%3F_m%3DGFuJpp8eT7 from pid=26469, uid=10215 requires the provider be exported, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1620)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1155)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:991)
at android.content.ContentResolver.openInputStream(ContentResolver.java:711)
at com.whatsapp.pe.<init>(GifUtils.java:86)
at com.whatsapp.pe.b(GifUtils.java:237)
at com.whatsapp.util.MediaFileUtils.f(MediaFileUtils.java:2280)
at com.whatsapp.util.MediaFileUtils.a(MediaFileUtils.java:557)
at com.whatsapp.ContactPicker.a(ContactPicker.java:1455)
at com.whatsapp.ContactPicker.a(ContactPicker.java:115)
at com.whatsapp.ContactPicker$6.a(ContactPicker.java:342)
at com.whatsapp.util.au.onClick(OnOneClickListener.java:15)
at android.view.View.performClick(View.java:5697)
at android.view.View$PerformClick.run(View.java:22526)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by thusoy** [comment]
This seems to have been fixed, can no longer reproduce with 2.5.0.
